# Generated by Django 4.0.6 on 2022-07-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_jobs_status_user_jobs_status_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs_status',
            old_name='posts',
            new_name='post',
        ),
    ]
