# Generated by Django 4.0.6 on 2022-07-08 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_rename_posts_jobs_status_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs_status',
            name='user',
        ),
        migrations.AddField(
            model_name='jobs_status',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
